import { createUseStyles } from 'react-jss';

import gradient from 'assets/images/about-page/what-is/gradient.png';
import { textWithGradient } from 'pages/about-page/styles';
import {
  MAX_WIDTH_1239,
  MAX_WIDTH_1439,
  MAX_WIDTH_767,
} from 'shared/constants';
import { IAppTheme } from 'shared/styles/theme';

export const useStyles = createUseStyles((theme: IAppTheme) => ({
  container: {
    color: theme.colors.white,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '1130px',
    marginInline: '155px',
    marginBlock: '100px',
    [MAX_WIDTH_1439]: {
      maxWidth: '875px',
      marginInline: 'auto',
      marginBlock: '77px',
    },
    [MAX_WIDTH_1239]: { maxWidth: '520px', marginBlock: '46px' },
    [MAX_WIDTH_767]: { maxWidth: '280px', marginBlock: '35px' },
  },
  content: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    [MAX_WIDTH_767]: { maxWidth: '280px' },
  },
  mainContent: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginBottom: '70px',
    gap: '32px',
    [MAX_WIDTH_1439]: { gap: '24px', marginBottom: '54px' },
    [MAX_WIDTH_1239]: { gap: '14px', marginBottom: '32px' },
    [MAX_WIDTH_767]: { flexDirection: 'column', marginBottom: '22px' },
  },
  title: {
    fontSize: '6rem',
    lineHeight: '5.625rem',
    marginBlock: '0px 60px',
    textTransform: 'uppercase',
    cursor: 'default',
    userSelect: 'none',
    ...textWithGradient,
    [MAX_WIDTH_1439]: {
      fontSize: '4.631rem',
      lineHeight: '4.341rem',
      marginBlock: '0px 56px',
    },
    [MAX_WIDTH_1239]: {
      fontSize: '2.746rem',
      lineHeight: '2.575rem',
      marginBlock: '0px 29px',
    },
    [MAX_WIDTH_767]: {
      maxWidth: '280px',
      marginInline: 'auto',
      marginBlock: '0px 20px',
    },
  },
  leftContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '36px',
    minWidth: '715px',
    height: '508px',
    position: 'relative',
    padding: '18px 20px 24px 25px',
    zIndex: 1,
    '&:after': {
      content: '""',
      width: '150%',
      height: '100%',
      backgroundImage: `url(${gradient})`,
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      opacity: '0.5',
      filter: 'blur(54px)',
      zIndex: -1,
    },
    [MAX_WIDTH_1439]: {
      padding: '14px 15px 18px 19px',
      gap: '28px',
      minWidth: '552px',
      height: '392px',
    },
    [MAX_WIDTH_1239]: {
      padding: '8px 9px 11px 11px',
      gap: '16px',
      minWidth: '327px',
      height: '232px',
    },
    [MAX_WIDTH_767]: {
      padding: '8px 0px 5px 4px',
      minWidth: '280px',
      height: '227px',
      order: 1,
    },
  },
  rightContent: {
    position: 'relative',
    background: theme.colors.secondaryDark,
    padding: '24px 28px',
    borderRadius: '10px',
    [MAX_WIDTH_1439]: { padding: '18px 7px 25px 24px', borderRadius: '7.7px' },
    [MAX_WIDTH_1239]: { padding: '11px 4px 14px 14px', borderRadius: '4.5px' },
    [MAX_WIDTH_767]: { padding: '11px 14px 14px 14px', order: 0 },
  },
  subContentTitle: {
    textTransform: 'uppercase',
    fontSize: '1.5rem',
    lineHeight: '2rem',
    marginBlock: '0px 32px',
    [MAX_WIDTH_1439]: {
      fontSize: '1.158ren',
      lineHeight: '1.544rem',
      marginBlock: '0px 24px',
    },
    [MAX_WIDTH_1239]: {
      fontSize: '0.687rem',
      lineHeight: '0.916rem',
      marginBlock: '0px 14px',
    },
    [MAX_WIDTH_767]: { marginBlock: '0px 17px' },
  },
  subContentContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '36px',
    [MAX_WIDTH_1439]: { gap: '28px' },
    [MAX_WIDTH_1239]: { gap: '16px' },
    [MAX_WIDTH_767]: { gap: '20px', flexWrap: 'wrap', flexDirection: 'row' },
  },
  subContentText: {
    position: 'relative',
    marginBlock: '0px',
    paddingLeft: '14px',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontFamily: theme.fonts.Everett.Light,
    '&:before': {
      content: '""',
      position: 'absolute',
      left: 0,
      width: '7px',
      height: '100%',
      background: theme.colors.white,
      borderRadius: '2px',
    },
    [MAX_WIDTH_1439]: {
      paddingLeft: '11px',
      fontSize: '0.676rem',
      lineHeight: '0.965rem',
      '&:before': { width: '5px' },
    },
    [MAX_WIDTH_1239]: {
      paddingLeft: '7px',
      fontSize: '0.401rem',
      lineHeight: '0.573rem',
      '&:before': { width: '3px' },
    },
    [MAX_WIDTH_767]: {
      height: 'fit-content',
      '&.i-1': { maxWidth: '105px' },
      '&.i-2': { maxWidth: '102px' },
      '&.i-3': { maxWidth: '105px' },
      '&.i-4': { maxWidth: '102px' },
    },
  },
  contentText: {
    marginBlock: '0px',
    fontSize: '1.25rem',
    lineHeight: '2rem',
    fontFamily: theme.fonts.Everett.Light,
    '& b': { fontFamily: theme.fonts.Everett.Medium },
    [MAX_WIDTH_1439]: { fontSize: '0.965rem', lineHeight: '1.544rem' },
    [MAX_WIDTH_1239]: { fontSize: '0.573rem', lineHeight: '0.916rem' },
  },
  socialLinks: {
    [MAX_WIDTH_767]: {
      position: 'absolute',
      bottom: '14px',
      right: '28px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '12px',
    },
  },
  socialLink: {
    [MAX_WIDTH_767]: { width: '13px', height: '13px' },
    '& path': { fill: theme.colors.white },
  },
  summaryContainer: {
    position: 'relative',
    borderTop: ['1px', 'solid', theme.colors.lightGrey],
    borderBottom: ['1px', 'solid', theme.colors.lightGrey],
    overflow: 'hidden',
    maxWidth: '1130px',
    [MAX_WIDTH_1439]: { maxWidth: '872px' },
    [MAX_WIDTH_1239]: { borderWidth: '0.5px', maxWidth: '517px' },
    [MAX_WIDTH_767]: { maxWidth: '100vw' },
  },
  summaryTitleContainer: {
    position: 'absolute',
    background: theme.colors.black,
    top: '50%',
    transform: 'translate(0%, -50%)',
    zIndex: 1,
    width: '440px',
    paddingRight: '10px',
    [MAX_WIDTH_1439]: { width: '336px' },
    [MAX_WIDTH_1239]: { width: '203px' },
    [MAX_WIDTH_767]: {
      position: 'relative',
      top: 'unset',
      transform: 'unset',
      maxWidth: '240px',
      width: '100%',
      textAlign: 'center',
      marginBlock: '50px 22px',
      paddingRight: 'unset',
    },
  },
  summaryTitle: {
    color: theme.colors.lightGrey,
    fontSize: '2rem',
    lineHeight: '2.25rem',
    paddingLeft: '37px',
    position: 'relative',
    marginBlock: '0px',
    textTransform: 'uppercase',
    '&:before': {
      content: '""',
      position: 'absolute',
      left: 0,
      width: '14px',
      height: '100%',
      borderRadius: '3px',
      background: theme.colors.secondaryDark,
    },
    [MAX_WIDTH_1439]: {
      fontSize: '1.544rem',
      lineHeight: '1.736rem',
      paddingLeft: '27px',
      '&:before': { width: '10px', borderRadius: '2px' },
    },
    [MAX_WIDTH_1239]: {
      fontSize: '0.916rem',
      lineHeight: '1.03rem',
      paddingLeft: '16px',
      '&:before': { width: '6px', borderRadius: '1.3px' },
    },
    [MAX_WIDTH_767]: {
      paddingLeft: 'unset',
      paddingTop: '23px',
      '&:before': {
        width: '64px',
        height: '6px',
        top: '0',
        left: '50%',
        transform: 'translate(-50%, 0%)',
      },
    },
  },
  marqueeContainer: {
    display: 'flex',
    gap: '33px',
    height: '208px',
    [MAX_WIDTH_1439]: { gap: '28px', height: '160px' },
    [MAX_WIDTH_1239]: { gap: '16px', height: '95px' },
    [MAX_WIDTH_767]: { gap: '16px', height: '68px' },
  },
  grantInfo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantInfoContent: {
    marginBlock: 0,
    fontSize: '1rem',
    lineHeight: '1.563rem',
    color: theme.colors.lightGrey,
    textTransform: 'upperCase',
    '&.i-1': { width: '199px' },
    '&.i-2': { width: '438px' },
    '&.i-3': { width: '257px' },
    '&.i-4': { width: '506px' },
    [MAX_WIDTH_1439]: {
      fontSize: '0.772rem',
      lineHeight: '1.206rem',
      '&.i-1': { width: '153px' },
      '&.i-2': { width: '338px' },
      '&.i-3': { width: '198px' },
      '&.i-4': { width: '390px' },
    },
    [MAX_WIDTH_1239]: {
      fontSize: '0.458rem',
      lineHeight: '0.715rem',
      '&.i-1': { width: '91px' },
      '&.i-2': { width: '200px' },
      '&.i-3': { width: '117px' },
      '&.i-4': { width: '231px' },
    },
  },
  arrowIcon: {
    transform: 'rotate(-90deg)',
    minWidth: '68px',
    height: '69px',
    '& path': { stroke: theme.colors.lightGrey },
    [MAX_WIDTH_1439]: { minWidth: '52px', height: '53px' },
    [MAX_WIDTH_1239]: { minWidth: '31px', height: '31px' },
  },
}));
