import { createUseStyles } from 'react-jss';

import {
  MAX_WIDTH_1239,
  MAX_WIDTH_1439,
  MAX_WIDTH_767,
} from 'shared/constants';
import { IAppTheme } from 'shared/styles/theme';

export const useStyles = createUseStyles((theme: IAppTheme) => ({
  mainInfoSectionWrapper: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    color: theme.colors.white,
  },
  eventTitleWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    marginBlock: '30px',
    [MAX_WIDTH_1439]: { gap: '18px', marginBlock: '25px' },
    [MAX_WIDTH_1239]: { gap: '15px', marginBlock: '20px 0px' },
    [MAX_WIDTH_767]: {
      gap: '8px',
      flexDirection: 'column',
      justifyContent: 'center',
    },
  },
  eventLogo: {
    width: '120px',
    height: '120px',
    [MAX_WIDTH_1439]: { width: '100px', height: '100px' },
    [MAX_WIDTH_1239]: { width: '70px', height: '70px' },
  },
  eventName: {
    fontSize: '2.5rem',
    marginBlock: 0,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    wordWrap: 'break-word',
    WebkitLineClamp: 2,
    [MAX_WIDTH_1439]: { fontSize: '2.1rem' },
    [MAX_WIDTH_1239]: { fontSize: '1.8rem' },
    [MAX_WIDTH_767]: { textAlign: 'center' },
  },
  eventDates: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    fontSize: '1.15rem',
    [MAX_WIDTH_1439]: { fontSize: '1rem' },
    [MAX_WIDTH_1239]: { fontSize: '0.9rem', gap: '10px' },
    [MAX_WIDTH_767]: { justifyContent: 'center' },
  },
  eventDatesIcon: {
    '& path': { fill: theme.colors.white },
    [MAX_WIDTH_1439]: { width: '18px', height: '18px' },
    [MAX_WIDTH_1239]: { width: '16px', height: '16px' },
  },
  eventTitleInfo: {
    flex: 1,
    [MAX_WIDTH_767]: {
      display: 'flex',
      flexDirection: 'column',
      gap: '10px',
    },
  },
  eventDescriptionWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    gap: '36px',
    alignItems: 'flex-start',
    justifyContent: 'space-evenly',
    marginBlock: '60px',
    '& a': { color: theme.colors.eventLinkColor },
    [MAX_WIDTH_1239]: {
      marginBlock: '50px',
    },
    [MAX_WIDTH_767]: {
      width: 'unset',
      flexDirection: 'column',
      marginInline: 'auto',
      marginBlock: '40px',
    },
  },
  eventDescriptionBlock: {
    width: '100%',
    maxWidth: '376px',
  },
  eventDescriptionBlockHeader: {
    margin: 0,
    fontSize: '1.5rem',
    textTransform: 'uppercase',
    marginBottom: '8px',
    [MAX_WIDTH_1239]: {
      fontSize: '1.2rem',
      marginBottom: '6px',
    },
  },
  eventDescriptionBlockBody: {
    margin: 0,
    color: theme.colors.grey,
    lineHeight: '1.4rem',
    '& ul': { paddingLeft: '15px' },
    [MAX_WIDTH_1239]: {
      fontSize: '0.95rem',
      lineHeight: '1.2rem',
    },
  },
  eventSocials: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '20px',
    marginBlock: '0px 25px',
    [MAX_WIDTH_1439]: { gap: '18px' },
    [MAX_WIDTH_1239]: { gap: '15px', marginBlock: '0px 20px' },
    [MAX_WIDTH_767]: { gap: '12px' },
  },
  socialLinkContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    padding: '10px',
    margin: 0,
    background: 'rgba(255, 255, 255, 0.1)',
    [MAX_WIDTH_1439]: { padding: '9px' },
    [MAX_WIDTH_1239]: { padding: '7px' },
    [MAX_WIDTH_767]: { padding: '5px' },
    '&:hover': {
      cursor: 'pointer',
      background: 'rgba(255, 255, 255, 0.12)',
      '& path': { fill: theme.colors.secondaryDark },
    },
  },
  socialLink: {
    width: '24px',
    height: '24px',
    [MAX_WIDTH_1439]: { width: '22px', height: '22px' },
    [MAX_WIDTH_1239]: { width: '20px', height: '20px' },
  },
  eventWebUrl: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '15px',
    fontSize: '1.15rem',
    color: theme.colors.white,
    marginBlock: '0px 25px',
    '& span': {
      maxWidth: '95%',
      textOverflow: 'ellipsis',
      overflow: 'hidden',
      whiteSpace: 'nowrap',
    },
    [MAX_WIDTH_1439]: {
      gap: '12px',
      fontSize: '1.1rem',
      marginBlock: '0px 25px',
    },
    [MAX_WIDTH_1239]: {
      gap: '8px',
      fontSize: '1rem',
      marginBlock: '0px 20px',
    },
  },
  eventWebUrlIcon: {
    width: '20px',
    height: '20px',
    marginBottom: '2px',
    transform: 'rotate(-45deg)',
    minWidth: '20px',
    minHeight: '20px',
    [MAX_WIDTH_1239]: {
      width: '18px',
      height: '18px',
      minWidth: '18px',
      minHeight: '18px',
    },
  },
}));
