import { createUseStyles } from 'react-jss';

import { textWithGradient } from 'pages/about-page/styles';
import {
  MAX_WIDTH_1239,
  MAX_WIDTH_1439,
  MAX_WIDTH_767,
} from 'shared/constants';
import { IAppTheme } from 'shared/styles/theme';
import { flexCenter } from 'shared/styles/themeUtils';

export const useStyles = createUseStyles((theme: IAppTheme) => ({
  container: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: '1600px',
    flex: 1,
    alignItems: 'center',
    padding: '60px 155px',
    color: theme.colors.white,
    [MAX_WIDTH_1439]: { padding: '40px 118px 60px' },
    [MAX_WIDTH_1239]: { padding: '40px 86px 60px' },
    [MAX_WIDTH_767]: { padding: '24px 40px 32px' },
  },
  wrapper: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    width: '100%',
  },
  eventScheduleSectionWrapper: {
    ...flexCenter,
    width: '100%',
    flexDirection: 'column',
    color: theme.colors.white,
  },
  scheduleCheckpoints: {
    ...flexCenter,
    flexDirection: 'column',
    width: '100%',
  },
  scheduleCheckpointsList: {
    maxWidth: '785px',
    marginInline: 'auto',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
    marginBlock: '25px',
    gap: '20px',
    [MAX_WIDTH_1439]: { gap: '18px' },
    [MAX_WIDTH_1239]: { marginBlock: '20px', gap: '15px' },
    [MAX_WIDTH_767]: { gap: '12px' },
  },
  scheduleCheckpoint: {
    position: 'relative',
    width: '100%',
    display: 'flex',
    gap: '20px',
    padding: '24px',
    color: theme.colors.white,
    background: theme.colors.lightDark,
    cursor: 'pointer',
    '&.now': { border: ['2px', 'solid', theme.colors.secondaryDark] },
    '&.ended': {
      '&::after': {
        content: '""',
        position: 'absolute',
        width: '100%',
        height: '100%',
        top: 0,
        left: 0,
        background: '#0000005c',
        zIndex: 0,
      },
    },
    '&.noProject': { cursor: 'default' },
    [MAX_WIDTH_1439]: { gap: '18px', padding: '22px' },
    [MAX_WIDTH_1239]: { gap: '15px', padding: '18px' },
    [MAX_WIDTH_767]: { gap: '10px', padding: '16px' },
  },
  scheduleCheckpointLogo: {
    minWidth: '80px',
    height: '80px',
    backgroundPosition: 'center center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'contain',
    border: ['1px', 'solid', theme.colors.grey],
    borderRadius: '50%',
    [MAX_WIDTH_1439]: { width: '75px', height: '75px', minWidth: '80px' },
    [MAX_WIDTH_1239]: { width: '70px', height: '70px', minWidth: '70px' },
    [MAX_WIDTH_767]: { width: '60px', height: '60px', minWidth: '60px' },
  },
  scheduleCheckpointLiveIcon: {
    position: 'absolute',
    top: 10,
    right: 20,
    '& path': { fill: theme.colors.secondaryDark },
    [MAX_WIDTH_1439]: { width: '20px', height: '20px', top: 7, right: 14 },
    [MAX_WIDTH_1239]: { width: '18px', height: '18px', top: 5, right: 10 },
    [MAX_WIDTH_767]: { width: '16px', height: '16px', top: 3, right: 6 },
  },
  scheduleCheckpointContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    [MAX_WIDTH_1239]: { gap: '5px' },
  },
  scheduleCheckpointTime: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontFamily: theme.fonts.Everett.Medium,
    margin: 0,
    '& .time-icon': { width: '18px', height: '18px' },
    [MAX_WIDTH_1439]: {
      fontSize: '0.95rem',
      gap: '8px',
      '& .time-icon': { width: '17px', height: '17px' },
    },
    [MAX_WIDTH_1239]: {
      fontSize: '0.9rem',
      gap: '6px',
      '& .time-icon': { width: '16px', height: '16px' },
    },
    [MAX_WIDTH_767]: {
      fontSize: '0.85rem',
      gap: '5px',
      '& .time-icon': { width: '15px', height: '15px' },
    },
  },
  scheduleCheckpointTitle: {
    fontSize: '1.25rem',
    margin: 0,
    [MAX_WIDTH_1439]: { fontSize: '1.2rem' },
    [MAX_WIDTH_1239]: { fontSize: '1.15rem' },
    [MAX_WIDTH_767]: { fontSize: '1.05rem' },
  },
  scheduleCheckpointDescription: {
    margin: 0,
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    wordWrap: 'break-word',
    WebkitLineClamp: 2,
    color: theme.colors.grey,
    [MAX_WIDTH_1439]: { fontSize: '0.95rem' },
    [MAX_WIDTH_1239]: { fontSize: '0.9rem' },
    [MAX_WIDTH_767]: { fontSize: '0.85rem' },
  },
  scheduleCheckpointsDaysWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '8px 10px',
    gap: '10px',
    background: theme.colors.lightDark,
    width: 'fit-content',
    fontFamily: theme.fonts.Everett.Medium,
    fontSize: '1.25rem',
    borderRadius: '5px',
    [MAX_WIDTH_1239]: {
      padding: '6px 8px',
      gap: '8px',
      fontSize: '1.2rem',
    },
    [MAX_WIDTH_767]: { padding: '5px 7px', fontSize: '1rem' },
  },
  scheduleCheckpointsDaysIcon: {
    marginBottom: '2px',
    '& path': { fill: theme.colors.white },
    [MAX_WIDTH_1439]: { width: '20px', height: '20px' },
    [MAX_WIDTH_1239]: { width: '18px', height: '18px' },
    [MAX_WIDTH_767]: { width: '16px', height: '16px' },
  },
  backBtnContainer: {
    position: 'sticky',
    top: 0,
    left: 0,
    color: theme.colors.white,
    width: '100%',
    padding: '20px',
    background: theme.colors.black,
    zIndex: 80,
    [MAX_WIDTH_1239]: { padding: '10px' },
  },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    color: theme.colors.white,
    fontSize: '1.5rem',
    '& svg': {
      width: '26px',
      height: '26px',
      marginBottom: '2px',
      color: theme.colors.white,
    },
    [MAX_WIDTH_1239]: {
      gap: '10px',
      fontSize: '1.25rem',
      '& svg': {
        width: '20px',
        height: '20px',
        marginBottom: '0',
      },
    },
  },
  titleWrapper: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: '3.9rem',
    marginBlock: '15px',
    userSelect: 'none',
    textTransform: 'uppercase',
    textAlign: 'center',
    ...textWithGradient,
    [MAX_WIDTH_1439]: { fontSize: '3.7rem' },
    [MAX_WIDTH_1239]: { fontSize: '3.2rem', marginBlock: '12px' },
    [MAX_WIDTH_767]: { fontSize: '2.4rem', marginBlock: '8px' },
  },
  watchBtn: {
    position: 'absolute',
    bottom: '18px',
    right: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    color: theme.colors.white,
    background: theme.colors.secondaryDark,
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '0.95rem',
    zIndex: 1,
    [MAX_WIDTH_1239]: {
      fontSize: '0.875rem',
    },
    [MAX_WIDTH_767]: {
      bottom: '14px',
      right: '14px',
      fontSize: '0.8rem',
    },
  },
  watchBtnIcon: {
    width: '16px',
    height: '16px',
    '& circle': {
      fill: theme.colors.white,
    },
    '& path': {
      fill: theme.colors.secondaryDark,
    },
    [MAX_WIDTH_767]: {
      width: '14px',
      height: '14px',
    },
  },
}));
